spring:
  application:
    name: mscartoes
  rabbitmq:
    host: msrabbitmq
    port: 5672
    username: guest
    password: guest


server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:123456@eureka-ms:8761/eureka
  instance:
    instance-id:  ${spring.application.name}:${spring.apllication.instance_id:${random.value} }

mq:
  queues:
    emissao-cartoes: emissao-cartoes